name: "Code style checking"
on: pull_request

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up checkpatch
        run: |
          wget 'https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl'
          chmod +x checkpatch.pl
          touch const_structs.checkpatch
          touch spelling.txt
      - name: Checkpatch
        run: |
          set -x
          git fetch origin
          git rev-parse HEAD
          git rev-parse origin/master
          echo SHA: $GITHUB_SHA
          echo REF: $GITHUB_REF
          make checkpatch CHECKPATCH=./checkpatch.pl Q=
